### ISSUE TITLE
Can not continue after password input

### ISSUE THREAD

**Issue by elethlad** [declantyson/doto#1]
I can not login after putting in my password, hitting Enter does nothing. 
Nothing was changed except replacing the appropriate API keys. I had to switch to another tty to resolve this, after rebooting again due to other unrelated issues I had the standard error message and had to choose a fallback theme.

I would like to help in fixing this, also is it possible to remove the weather and news widgets without too much hassle or should I start from scratch?

**Comment by declantyson** [comment]
Hi @elethlad, please go ahead and fix it. You should be able to remove the widgets simply by removing widgets.js from the HTML file and the function call from start.js

Please let me know if you have any progress.

**Comment by declantyson** [comment]
@elethlad What is your distro?

**Comment by elethlad** [comment]
Sorry, I did not see the notification, @declantyson.
I am using archlinux.

**Comment by skrambol** [comment]
@elethlad kindly check my [comment](https://github.com/declantyson/doto/issues/10#issuecomment-334925636) at issue #10 and see if it works for you.
