### ISSUE TITLE
No DE selection

### ISSUE THREAD

**Issue by maxnatamo** [declantyson/doto#2]
I have both GNOME and i3 - using i3.

When logged in lightdm logs in to GNOME, by default.

**Comment by declantyson** [comment]
Hi @madstk1 

I've not tested on any DE outside Unity - I'll take a look when I have a chance but if you have any ideas that would be great.

**Comment by skrambol** [comment]
@madstk1 while the DE selection is in development (or planning), you might opt to change your `user-session` found in `/etc/lightdm/lightdm/conf` to your preferred DE to fix this. For example
```
user-session=i3
```

**Comment by skrambol** [comment]
@declantyson I'm currently working on this. I'm close to finishing this one. Just gonna test it on multiple users. I will make a pr as soon as possible.
