### ISSUE TITLE
Expose settings more nicely for users

### ISSUE THREAD

**Issue by declantyson** [declantyson/doto#4]
- A user should be able to change settings for:
    - Weather location
    - News sources
    - AJAX on/off

A chrome user should be able to do this through the UI
If possible for lightdm users too, if not then provide a JSON file

**Comment by skrambol** [comment]
I'm new to LightDM/Chrome extension development but kindly look into my pull request.

**Comment by declantyson** [comment]
@systemplado 

Have merged your PR, but keeping this open for now while I think about a UI implementation. Thanks for your contribution!

**Comment by declantyson** [comment]
Closed by #11.
