### ISSUE TITLE
CORS request scheme error

### ISSUE THREAD

**Issue by charveey** [declantyson/doto#8]
Everything is okay but widget don't appear on LightDM. When I launch `lightdm-webkit2-greeter` from terminal I get the following error:
 `** (WebKitWebProcess:12616): WARNING **: request scheme error: https
file:///usr/share/lightdm-webkit/themes/doto/assets/widgets.js:18:17: CONSOLE ERROR XMLHttpRequest cannot load https://newsapi.org/v1/articles?apiKey=472664a6fdfd49608e07ba8eb6839f98&source=ars-technica&sortBy=top due to access control checks.`...
The only things I edited are APIs and news feeds

**Comment by declantyson** [comment]
Hi @charveey 

What's your distro?

**Comment by charveey** [comment]
I'm running ZorinOS 12 (xenial)

**Comment by declantyson** [comment]
Interesting - haven't heard of that one before but looks like it's an Ubuntu derivative so it should be OK. Can I just check your network connection is available to all users?

**Comment by charveey** [comment]
I've already enabled it (via network-manager). In addition there is another account on the computer which can use network

**Comment by skrambol** [comment]
@declantyson It's [Hacktoberfest 2017](https://hacktoberfest.digitalocean.com/) and you might want to add ```hacktoberfest``` tags or ```up-for-grabs``` tags in to some issues so that more people can see them.

**Comment by declantyson** [comment]
@systemplado Great idea, have done so.

**Comment by skrambol** [comment]
@charveey  I've found a fix!!!! FINALLY!
Try changing your `lightdm-webkit2-greeter.conf` to the following or maybe something similar.
Take note of the `secure_mode` setting under the `greeter` part.

```conf
[greeter]
debug_mode          = false
detect_theme_errors = true
screensaver_timeout = 300
secure_mode         = false #this is the setting we need!!
time_format         = LT
time_language       = auto
webkit_theme        = doto
```

UPDATE: I guess this only works for the weather and the news. Loading the `mp4` files are still not working for me.

@declantyson kindly share your config if you have changed it same as above. Maybe this error only persists on other distros.

**Comment by declantyson** [comment]
@systemplado This is good stuff - I'm away for the next few days but when I return I'll post you my config.
